version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8081:8081"
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     -  "express"
  redis:
    image: redis:alpine